[project]
name = "bcr_signaling"
version = "0.1.0"
description = "b cell receptor (bcr) signaling simulator"
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
